# Generated by Django 5.1.4 on 2025-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactmessage",
            name="name",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="first_name",
            field=models.CharField(default="john", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="last_name",
            field=models.CharField(default="doe", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
