# Generated by Django 5.1.4 on 2025-06-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="full_name",
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=50),
            preserve_default=False,
        ),
    ]
