# Generated by Django 5.1.4 on 2025-06-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_brand_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["name"]},
        ),
    ]
