# Generated by Django 5.1.4 on 2025-04-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', help_text='e.g. Gibson, Martin, Yamaha, Fender, etc.', max_length=100),
        ),
    ]
