# Generated by Django 5.1.4 on 2025-04-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cloudinary_image_url",
            field=models.URLField(
                blank=True,
                help_text="Optional Cloudinary image URL.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
