# Generated by Django 5.1.4 on 2025-04-27 21:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_cloudinary_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cloudinary_image_url",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload product image to Cloudinary.",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
